### ISSUE TITLE
Does not work on Unraid 6.10-RC1

### ISSUE THREAD

**Issue by grizzy255** [rezo552/unraid-swtpm#1]
Installed in /boot/extra

root@Jarvis:/boot/extra# ls -al
total 2640
drwx------  2 root root   16384 Sep 20 13:36 ./
drwx------ 13 root root   16384 Jan  1  1970 ../
-rw-------  1 root root  190644 Sep 20 13:33 libseccomp.txz
-rw-------  1 root root 1781908 Sep 20 13:33 libtpms.txz
-rw-------  1 root root  673376 Jul  3 03:10 swtpm_final.txz
root@Jarvis:/boot/extra# 

After a reboot, the libvirt/swtpm directory is empty.

root@Jarvis:/var/lib/libvirt/swtpm# ls -al
total 0
drwxr-xr-x  2 root root  40 May  6 03:31 ./
drwxr-xr-x 10 root root 200 May  6 03:31 ../
root@Jarvis:/var/lib/libvirt/swtpm# 

Unraid log 

Sep 20 14:24:14 Jarvis winbindd[2249]:   daemon_ready: daemon 'winbindd' finished starting up and ready to serve connections

Sep 20 14:24:15 Jarvis root: Installing /boot/extra packages
Sep 20 14:24:15 Jarvis root: Installing plugins

**Comment by rezo552** [comment]
What does "which swtpm" say? Have you tried to run a machine with TPM?

**Comment by grizzy255** [comment]
Server# which swtpm
/usr/bin/swtpm

I have added the OVMF files to the VM and XML edits for the TPM chip. This is a WIN-11 VM.
When I start the VM I get an error 

internal error: Could not run '/usr/bin/swtpm_setup'. exitstatus: 1; Check error log '/var/log/swtpm/libvirt/qemu/Windows 11-swtpm.log' for details.


root@Jarvis:/var/lib/libvirt/swtpm# cat /var/log/swtpm/libvirt/qemu/Windows\ 11-swtpm.log 
Starting vTPM manufacturing as root:tss @ Mon Sep 20 16:10:52 2021
Error: Could not start the TPM 2.
Error: An error occurred. Authoring the TPM state failed.
Ending vTPM manufacturing @ Mon Sep 20 16:10:57 2021
Starting vTPM manufacturing as root:tss @ Mon Sep 20 16:15:14 2021
Error: Could not start the TPM 2.
Error: An error occurred. Authoring the TPM state failed.
Ending vTPM manufacturing @ Mon Sep 20 16:15:19 2021


root@Jarvis:/usr/bin# ./swtpm_setup
Could not get account data of user tss.

**Comment by rezo552** [comment]
yes, you need to use the startup the script. That will create the symlink and set the permission on the folder

**Comment by grizzy255** [comment]
Got it working - thank you. Had to use the strap script.



​
